name: MoneyPluginBridge
main: MinecrafterJPN\MoneyPluginBridge
author: MinecrafterJPN
version: 1.0
api: [1.6.0]
load: POSTWORLD
description: Bridges among money plugins
website: https://github.com/MinecrafterJPN/MonePluginBridge/
